[project]
name = "frontend"
version = "0.1.0"
description = "List of Winter and Summer Schools"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "Flask>=3.0.3",
]

[project.scripts]
app = "api.index:app"